"""m3: transformers + profiles + listings + inquiries + ratings

Revision ID: 7be0c5635862
Revises: 220b1de397e4
Create Date: 2026-05-25 11:00:29.017908+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '7be0c5635862'
down_revision: Union[str, None] = '220b1de397e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transformers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('geo', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transformers'))
    )
    # `idx_transformers_geo` is auto-created by GeoAlchemy2 on the Geography column.
    op.create_index(op.f('ix_transformers_city'), 'transformers', ['city'], unique=False)
    op.create_index(op.f('ix_transformers_code'), 'transformers', ['code'], unique=True)
    op.create_table('listings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('day_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('night_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('capacity_kwh', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('capacity_kwh > 0', name=op.f('ck_listings_capacity_positive')),
    sa.CheckConstraint('day_rate >= 0', name=op.f('ck_listings_day_rate_non_negative')),
    sa.CheckConstraint('night_rate IS NULL OR night_rate >= 0', name=op.f('ck_listings_night_rate_non_negative')),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], name=op.f('fk_listings_seller_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listings'))
    )
    op.create_index(op.f('ix_listings_seller_id'), 'listings', ['seller_id'], unique=False)
    op.create_table('profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('whatsapp_e164', sa.String(length=32), nullable=True),
    sa.Column('address_text', sa.String(length=300), nullable=True),
    sa.Column('geo', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('transformer_id', sa.UUID(), nullable=True),
    sa.Column('monthly_demand_kwh', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transformer_id'], ['transformers.id'], name=op.f('fk_profiles_transformer_id_transformers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_profiles'))
    )
    # `idx_profiles_geo` is auto-created by GeoAlchemy2 on the Geography column.
    op.create_index(op.f('ix_profiles_transformer_id'), 'profiles', ['transformer_id'], unique=False)
    op.create_table('inquiries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], name=op.f('fk_inquiries_buyer_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('fk_inquiries_listing_id_listings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], name=op.f('fk_inquiries_seller_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inquiries'))
    )
    op.create_index(op.f('ix_inquiries_buyer_id'), 'inquiries', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_inquiries_listing_id'), 'inquiries', ['listing_id'], unique=False)
    op.create_index(op.f('ix_inquiries_seller_id'), 'inquiries', ['seller_id'], unique=False)
    op.create_table('ratings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('rater_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('inquiry_id', sa.UUID(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('text_body', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('stars BETWEEN 1 AND 5', name=op.f('ck_ratings_stars_range')),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], name=op.f('fk_ratings_inquiry_id_inquiries'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rater_id'], ['users.id'], name=op.f('fk_ratings_rater_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['users.id'], name=op.f('fk_ratings_target_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ratings')),
    sa.UniqueConstraint('rater_id', 'target_id', 'inquiry_id', name='one_rating_per_interaction')
    )
    op.create_index(op.f('ix_ratings_rater_id'), 'ratings', ['rater_id'], unique=False)
    op.create_index(op.f('ix_ratings_target_id'), 'ratings', ['target_id'], unique=False)
    # NOTE: `spatial_ref_sys` is a PostGIS-owned table — never drop it.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: never re-create `spatial_ref_sys` — PostGIS owns it.
    op.drop_index(op.f('ix_ratings_target_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_rater_id'), table_name='ratings')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_inquiries_seller_id'), table_name='inquiries')
    op.drop_index(op.f('ix_inquiries_listing_id'), table_name='inquiries')
    op.drop_index(op.f('ix_inquiries_buyer_id'), table_name='inquiries')
    op.drop_table('inquiries')
    op.drop_index(op.f('ix_profiles_transformer_id'), table_name='profiles')
    op.drop_index('idx_profiles_geo', table_name='profiles', postgresql_using='gist')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_listings_seller_id'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_transformers_code'), table_name='transformers')
    op.drop_index(op.f('ix_transformers_city'), table_name='transformers')
    op.drop_index('idx_transformers_geo', table_name='transformers', postgresql_using='gist')
    op.drop_table('transformers')
    # ### end Alembic commands ###
